# Generated by Django 5.2.4 on 2025-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateTimeField(null=True)),
                ('starred', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('notes', models.TextField(null=True)),
                ('time_mins', models.IntegerField(null=True)),
                ('energy', models.IntegerField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], null=True)),
                ('due_date', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
